### ISSUE TITLE
要素1つの配列を生成できるように

### ISSUE THREAD

**Issue by SatooRu65536** [SatooRu65536/ncss#1]
要素1つの配列を作るのに2つ以上で宣言後に代入する必要がある

**Comment by SatooRu65536** [comment]
まあいっか。
```css
#main {
    --arr: 1 2;
    transform: --arr 1;
    content: var(--arr);
}
```
