### ISSUE TITLE
配列が正しく処理されない

### ISSUE THREAD

**Issue by SatooRu65536** [SatooRu65536/ncss#11]
二次元配列になる
```css
#main {
    --arr: 1 2 3;    /* [1, 2, 3] */
    transform: --arr push(--arr 4 5);
    content: var(--arr);     /* [[1, 2, 3, 4, 5]] */
}
```
