### ISSUE TITLE
2次元配列の扱い

### ISSUE THREAD

**Issue by SatooRu65536** [SatooRu65536/ncss#3]
2次元配列を生成できるがどう扱うか
```css
--arr-1: 1 2 3 4;
--arr-2: var(--arr-1) var(--arr-1);
content: var(--arr-2);
```

**Comment by SatooRu65536** [comment]
面倒だから非推奨
```css
#main {
    /* 2次元配列 生成 */
    --arr: 1 2 3;
    --arr2: var(--arr) var(--arr);
    content: var(--arr2);

    /* 2次元配列 取得 */
    --arr3: arr(--arr2 1);
    content: arr(--arr3 1);
}
```
