### ISSUE TITLE
自作関数の戻り値の取得方法

### ISSUE THREAD

**Issue by SatooRu65536** [SatooRu65536/ncss#6]
戻り値の取得方法を考える

**Comment by SatooRu65536** [comment]
```css
#main {
    sub: '';
    result: --res1 --res2;
}
#sub {
    return: "penguin" 65536;
}
```
