### ISSUE TITLE
scssのエラー回避構文

### ISSUE THREAD

**Issue by SatooRu65536** [SatooRu65536/ncss#7]
同じプロパティを使った時にでるエラーを回避するための構文が欲しい
```css
#main {
    content: "Hello, World!";
    content: "Penguin is cute!";
}
```
↓
```css
#main {
    .hello_world {
        content: "Hello, World!";
    }

    .about_penguin {
        content: "Penguin is cute!";
    }
}
```
